--
-- Copyright (C) 2019  Andreas Lüthi
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>

local utils = {}

-- interpret buffer according to https://www.stockflightsystems.com/tl_files/downloads/canaerospace/canas_17.pdf
-- WIP: to be extended !
local function getValue4DataType(buffer, dataType)
    if buffer:len() < 4 then return buffer end

    if dataType == 2 then -- FLOAT
        return buffer:float()
    elseif dataType == 3 then -- LONG
        return buffer:int()
    elseif dataType == 4 then -- ULONG
        return buffer:uint()
    elseif dataType == 5 then -- BLONG
        return string.format("0x%08X", buffer:uint())
    elseif dataType == 6 then -- SHORT
        return buffer(0, 2):int()
    elseif dataType == 7 then -- USHORT
        return buffer(0, 2):uint()
    elseif dataType == 8 then -- BSHORT
        return string.format("0x%04X", buffer(0, 2):uint())
    elseif dataType == 9 then -- CHAR
        return buffer(0, 1):int()
    elseif dataType == 10 then -- UCHAR
        return buffer(0, 1):uint()
    elseif dataType == 11 then -- BCHAR
        return string.format("0x%02X", buffer(0, 1):uint())
    elseif dataType == 12 then -- SHORT2
        return buffer(0, 2):int() .. ", " .. buffer(2, 2):int()
    elseif dataType == 13 then -- USHORT2
        return buffer(0, 2):uint() .. ", " .. buffer(2, 2):uint()
    elseif dataType == 14 then -- BSHORT2
        return string.format("0x%04X, 0x%04X", buffer(0, 2):uint(), buffer(2, 2):uint())
    elseif dataType == 15 then -- CHAR4
        return buffer(0, 1):int() .. ", " .. buffer(1, 1):int() .. ", " .. buffer(2, 1):int() .. ", " .. buffer(3, 1):int()
    elseif dataType == 16 then -- UCHAR4
        return buffer(0, 1):uint() .. ", " .. buffer(1, 1):uint() .. ", " .. buffer(2, 1):uint() .. ", " .. buffer(3, 1):uint()
    elseif dataType == 17 then -- BCHAR4
        return string.format("0x%02X, 0x%02X, 0x%02X, 0x%02X", buffer(0, 1):uint(), buffer(1, 1):uint(), buffer(2, 1):uint(), buffer(3, 1):uint())
    elseif dataType == 18 then -- CHAR2
        return buffer(0, 1):int() .. ", " .. buffer(1, 1):int()
    elseif dataType == 19 then -- UCHAR2
        return buffer(0, 1):uint() .. ", " .. buffer(1, 1):uint()
    elseif dataType == 20 then -- BCHAR2
        return string.format("0x%02X, 0x%02X", buffer(0, 1):uint(), buffer(1, 1):uint())
    elseif dataType == 21 then -- MEMID
        return "MEMID: " .. buffer:uint()
    elseif dataType == 22 then -- CHKSUM
        return "CHKSUM: " .. buffer:uint()
    elseif dataType == 23 then -- ACHAR
        return "'" .. buffer(0, 1):string() .. "'"
    elseif dataType == 30 then -- DOUBLEH
        return "DOUBLEH: " .. buffer:uint()
    elseif dataType == 31 then -- DOUBLEL
        return "DOUBLEL: " .. buffer:uint()
    else
        return buffer
    end
end

local function formatSpeed(value) return value .. " m/s" end
local function formatDegree(value) return value / 1E7 .. " deg" end
local function formatAcceleration(value) return value .. " m/s2" end
local function formatRate(value) return value .. " deg/s" end
local function formatAngle(value) return value .. " deg" end
local function formatPercent(value) return value .. " %" end
local function formatAltitude(value) return value .. " m" end
local function formatPressure(value) return value .. " hPa" end
local function formatTemperature(value) return value .. " K" end
local function formatVoltage(value) return value .. " V" end
local function formatCurrent(value) return value .. " A" end
local function formatFrequency(value) return value .. " MHz" end
local function formatFlow(value) return value .. " kg/h" end
local function formatTorque(value) return value .. " Nm" end
local function formatUnknown(value) return value .. " ???" end

-- format value according to https://files.stockflightsystems.com/_5_CANaerospace/canas_17.pdf
-- WIP: to be extended !
local canIdFormattingTable = {
    [300]  = formatAcceleration,
    [301]  = formatAcceleration,
    [302]  = formatAcceleration,
    [303]  = formatRate,
    [304]  = formatRate,
    [305]  = formatRate,
    [306]  = formatPercent,
    [307]  = formatPercent,
    [308]  = formatPercent,
    [309]  = formatPercent,
    [310]  = formatPercent,
    [311]  = formatAngle,
    [312]  = formatAngle,
    [313]  = formatAngle,
    [314]  = formatSpeed,
    [315]  = formatSpeed,
    [316]  = formatSpeed,
    [317]  = formatSpeed,
    [320]  = formatAltitude,
    [321]  = formatAngle,
    [322]  = formatAltitude,
    [323]  = formatTemperature,
    [324]  = formatTemperature,
    [325]  = formatPressure,
    [326]  = formatPressure,
    [327]  = formatRate,
    [330]  = formatAltitude,
    [331]  = formatRate,
    [332]  = formatAltitude,
    [333]  = formatSpeed,
    [334]  = formatAngle,
    [335]  = formatTemperature,
    [336]  = formatSpeed,
    [337]  = formatSpeed,
    [338]  = formatSpeed,
    [339]  = formatPressure,
    [340]  = formatPercent,
    [342]  = formatPercent,
    [348]  = formatSpeed,
    [349]  = formatSpeed,
    [350]  = formatPressure,
    [345]  = formatSpeed,
    [500]  = formatPercent,
    [501]  = formatPercent,
    [502]  = formatPercent,
    [503]  = formatPercent,
    [504]  = formatPercent,
    [505]  = formatPercent,
    [506]  = formatPercent,
    [507]  = formatPercent,
    [508]  = formatTorque,
    [509]  = formatTorque,
    [510]  = formatTorque,
    [511]  = formatTorque,
    [512]  = formatTemperature,
    [513]  = formatTemperature,
    [514]  = formatTemperature,
    [515]  = formatTemperature,
    [516]  = formatTemperature,
    [517]  = formatTemperature,
    [518]  = formatTemperature,
    [519]  = formatTemperature,
    [520]  = formatTemperature,
    [521]  = formatTemperature,
    [522]  = formatTemperature,
    [523]  = formatTemperature,
    [524]  = formatFlow,
    [525]  = formatFlow,
    [526]  = formatFlow,
    [527]  = formatFlow,
    [528]  = formatPressure,
    [529]  = formatPressure,
    [530]  = formatPressure,
    [531]  = formatPressure,
    [532]  = formatPressure,
    [533]  = formatPressure,
    [534]  = formatPressure,
    [535]  = formatPressure,
    [536]  = formatTemperature,
    [537]  = formatTemperature,
    [538]  = formatTemperature,
    [539]  = formatTemperature,
    [540]  = formatTemperature,
    [541]  = formatTemperature,
    [542]  = formatTemperature,
    [543]  = formatTemperature,
    [564]  = formatPercent,
    [565]  = formatPercent,
    [566]  = formatPercent,
    [567]  = formatPercent,
    [568]  = formatPercent,
    [569]  = formatPercent,
    [570]  = formatPercent,
    [571]  = formatPercent,
    [572]  = formatTorque,
    [573]  = formatTorque,
    [574]  = formatTorque,
    [575]  = formatTorque,
    [576]  = formatTemperature,
    [577]  = formatTemperature,
    [578]  = formatTemperature,
    [579]  = formatTemperature,
    [580]  = formatTemperature,
    [581]  = formatTemperature,
    [582]  = formatTemperature,
    [583]  = formatTemperature,
    [584]  = formatTemperature,
    [585]  = formatTemperature,
    [586]  = formatTemperature,
    [587]  = formatTemperature,
    [588]  = formatFlow,
    [589]  = formatFlow,
    [590]  = formatFlow,
    [591]  = formatFlow,
    [592]  = formatPressure,
    [593]  = formatPressure,
    [594]  = formatPressure,
    [595]  = formatPressure,
    [596]  = formatPressure,
    [597]  = formatPressure,
    [598]  = formatPressure,
    [599]  = formatPressure,
    [600]  = formatTemperature,
    [601]  = formatTemperature,
    [602]  = formatTemperature,
    [603]  = formatTemperature,
    [604]  = formatTemperature,
    [605]  = formatTemperature,
    [606]  = formatTemperature,
    [607]  = formatTemperature,
    [612]  = formatTemperature,
    [613]  = formatTemperature,
    [614]  = formatTemperature,
    [615]  = formatTemperature,
    [660]  = formatFlow,
    [661]  = formatFlow,
    [662]  = formatFlow,
    [663]  = formatFlow,
    [664]  = formatFlow,
    [665]  = formatFlow,
    [666]  = formatFlow,
    [667]  = formatFlow,
    [676]  = formatTemperature,
    [677]  = formatTemperature,
    [678]  = formatTemperature,
    [679]  = formatTemperature,
    [680]  = formatTemperature,
    [681]  = formatTemperature,
    [682]  = formatTemperature,
    [683]  = formatTemperature,
    [684]  = formatPressure,
    [685]  = formatPressure,
    [686]  = formatPressure,
    [687]  = formatPressure,
    [688]  = formatPressure,
    [689]  = formatPressure,
    [690]  = formatPressure,
    [691]  = formatPressure,
    [712]  = formatPressure,
    [713]  = formatPressure,
    [714]  = formatPressure,
    [715]  = formatPressure,
    [716]  = formatPressure,
    [717]  = formatPressure,
    [718]  = formatPressure,
    [719]  = formatPressure,
    [720]  = formatTemperature,
    [721]  = formatTemperature,
    [722]  = formatTemperature,
    [723]  = formatTemperature,
    [724]  = formatTemperature,
    [725]  = formatTemperature,
    [726]  = formatTemperature,
    [727]  = formatTemperature,
    [800]  = formatPressure,
    [801]  = formatPressure,
    [802]  = formatPressure,
    [803]  = formatPressure,
    [804]  = formatPressure,
    [805]  = formatPressure,
    [806]  = formatPressure,
    [807]  = formatPressure,
    [808]  = formatTemperature,
    [809]  = formatTemperature,
    [810]  = formatTemperature,
    [811]  = formatTemperature,
    [812]  = formatTemperature,
    [813]  = formatTemperature,
    [814]  = formatTemperature,
    [815]  = formatTemperature,
    [900]  = formatVoltage,
    [901]  = formatVoltage,
    [902]  = formatVoltage,
    [903]  = formatVoltage,
    [904]  = formatVoltage,
    [905]  = formatVoltage,
    [906]  = formatVoltage,
    [907]  = formatVoltage,
    [908]  = formatVoltage,
    [909]  = formatVoltage,
    [910]  = formatCurrent,
    [911]  = formatCurrent,
    [912]  = formatCurrent,
    [913]  = formatCurrent,
    [914]  = formatCurrent,
    [915]  = formatCurrent,
    [916]  = formatCurrent,
    [917]  = formatCurrent,
    [918]  = formatCurrent,
    [919]  = formatCurrent,
    [920]  = formatVoltage,
    [921]  = formatVoltage,
    [922]  = formatVoltage,
    [923]  = formatVoltage,
    [924]  = formatVoltage,
    [925]  = formatVoltage,
    [926]  = formatVoltage,
    [927]  = formatVoltage,
    [928]  = formatVoltage,
    [929]  = formatVoltage,
    [930]  = formatCurrent,
    [931]  = formatCurrent,
    [932]  = formatCurrent,
    [933]  = formatCurrent,
    [934]  = formatCurrent,
    [935]  = formatCurrent,
    [936]  = formatCurrent,
    [937]  = formatCurrent,
    [938]  = formatCurrent,
    [939]  = formatCurrent,
    [940]  = formatCurrent,
    [941]  = formatCurrent,
    [942]  = formatCurrent,
    [943]  = formatCurrent,
    [944]  = formatCurrent,
    [945]  = formatCurrent,
    [946]  = formatCurrent,
    [947]  = formatCurrent,
    [948]  = formatCurrent,
    [949]  = formatCurrent,
    [1000] = formatDegree,
    [1001] = formatDegree,
    [1003] = formatAltitude,
    [1004] = formatSpeed,
    [1005] = formatAngle,
    [1006] = formatAngle,
    [1017] = formatDegree,
    [1018] = formatDegree,
    [1019] = formatAltitude,
    [1023] = formatAltitude,
    [1027] = formatAltitude,
    [1036] = formatDegree,
    [1037] = formatDegree,
    [1039] = formatSpeed,
    [1040] = formatAngle,
    [1041] = formatAngle,
    [1049] = formatDegree,
    [1050] = formatDegree,
    [1052] = formatSpeed,
    [1053] = formatAngle,
    [1054] = formatAngle,
    [1059] = formatDegree,
    [1060] = formatDegree,
    [1062] = formatSpeed,
    [1063] = formatAngle,
    [1064] = formatAngle,
    [1069] = formatAngle,
    [1070] = formatAltitude,
    [1079] = formatSpeed,
    [1080] = formatSpeed,
    [1081] = formatSpeed,
    [1082] = formatSpeed,
    [1083] = formatAngle,
    [1084] = formatAngle,
    [1085] = formatAngle,
    [1086] = formatAngle,
    [1100] = formatFrequency,
    [1101] = formatFrequency,
    [1102] = formatFrequency,
    [1103] = formatFrequency,
    [1104] = formatFrequency,
    [1105] = formatFrequency,
    [1106] = formatFrequency,
    [1107] = formatFrequency,
    [1108] = formatFrequency,
    [1109] = formatFrequency,
    [1110] = formatFrequency,
    [1111] = formatFrequency,
    [1120] = formatAngle,
    [1121] = formatAngle,
    [1122] = formatAngle,
    [1123] = formatAngle,
    [1124] = formatSpeed,
    [1125] = formatAngle,
    [1126] = formatAngle,
    [1127] = formatAngle,
    [1128] = formatAngle,
    [1129] = formatAngle,
    [1130] = formatSpeed,
    [1131] = formatSpeed,
    [1132] = formatSpeed,
    [1133] = formatAngle,
    [1134] = formatUnknown,
    [1135] = formatUnknown,
    [1177] = formatPressure,
    [1178] = formatPressure,
    [1179] = formatPressure,
    [1180] = formatPressure,
    [1200] = function(value) return value(0, 1):uint() .. ":" .. value(1, 1):uint() .. ":" .. string.format("%02d", value(2, 1):uint()) .. " utc" end,
    [1201] = formatPressure,
    [1202] = formatAltitude,
    [1203] = formatTemperature,
    [1206] = function(value) return value(0, 1):uint() .. "." .. value(1, 1):uint() + 1 .. "." .. value(2, 1):uint() .. value(3, 1):uint() .. " date" end,

    [1500] = formatTemperature,
    [1501] = formatPressure,
    [1502] = formatAcceleration,
    [1503] = formatAcceleration,
    [1504] = formatAcceleration
}

local function getValue4CanId(value, canId)
    local formatFunc = canIdFormattingTable[canId]
    if formatFunc then
        return formatFunc(value)
    else
        return value
    end
end

function utils.getValue(buffer, dataType, canId)
    return getValue4CanId(getValue4DataType(buffer, dataType), canId)
end

-- default identifier, see https://www.stockflightsystems.com/tl_files/downloads/canaerospace/canas_17.pdf
-- WIP: to be completed !
utils.defaultIdentifierTable = {
    [300] = "Body Longitudinal Acceleration",
    [301] = "Body Lateral Acceleration",
    [302] = "Body Normal Acceleration",
    [303] = "Body Pitch Rate",
    [304] = "Body Roll Rate",
    [305] = "Body Yaw Rate",
    [306] = "Rudder Position",
    [307] = "Stabilizer Position",
    [308] = "Elevator Position",
    [309] = "Left Aileron Position",
    [310] = "Right Aileron Position",
    [311] = "Body Pitch Angle",
    [312] = "Body Roll Angle",
    [313] = "Body Sideslip",
    [314] = "Altitude Rate",
    [315] = "Indicated Airspeed",
    [316] = "True Airspeed",
    [317] = "Calibrated Airspeed",
    [318] = "Mach Number",
    [319] = "Baro Correction",
    [320] = "Baro Corrected Altitude",
    [321] = "Heading Angle",
    [322] = "Standard Altitude",
    [323] = "Total Air Temperature [K]",
    [324] = "Static Air Temperature [K]",
    [325] = "Differential Pressure [hPa]",
    [326] = "Static Pressure [hPa]",
    [327] = "Heading Rate",
    [328] = "Port Side Angle Of Attack",
    [329] = "Starbord Side Angle Of Attack",
    [330] = "Density Altitude",
    [331] = "Turn Coordination Rate",
    [332] = "True Altitude",
    [333] = "Wind Speed",
    [334] = "Wind Direction",
    [335] = "Outside Air Temperature [K]",
    [336] = "Body Normal Velocity",
    [337] = "Body Longitudinal Velocity",
    [338] = "Body Lateral Velocity",
    [339] = "Total Pressure [hPa]",
    [340] = "Flaps Position",
    [341] = "Slats Position",
    [342] = "Speed Brake Position",
    [343] = "Spoiler Position",
    [344] = "Total Velocity",
    [345] = "Vertical Speed Of The Airmass",
    [346] = "Port Horizontal Tail Angle Of Attack",
    [347] = "Starboard Horizontal Tail Angle Of Attack",
    [348] = "TEK Altitude Rate",
    [349] = "TEK Altitude altitude",
    [350] = "TEK pressure",
    [354] = "Vertical speed of the airmass earth NED (negative is lift)",

    [400] = "Pitch Control Position",
    [401] = "Roll Control Position",
    [402] = "Lateral Stick Trim Position Command",
    [403] = "Yaw Control Position",
    [404] = "Collective Control Position",
    [405] = "Longitudinal Stick Trim Position Command",
    [406] = "Directional Pedals Trim Position Command",
    [407] = "Collective Lever Trim Position Command",
    [408] = "Cyclic Control Stick Switches",
    [409] = "Lateral Trim Speed",
    [410] = "Longitudinal Trim Speed",
    [411] = "Pedal Trim Speed",
    [412] = "Collective Trim Speed",
    [413] = "Nose Wheel Steering Handle Position",
    [414] = "Engine 1 Throttle Lever Position Ecs Channel A",
    [415] = "Engine 2 Throttle Lever Position Ecs Channel A",
    [416] = "Engine 3 Throttle Lever Position Ecs Channel A",
    [417] = "Engine 4 Throttle Lever Position Ecs Channel A",
    [418] = "Engine 1 Condition Lever Position Ecs Channel A",
    [419] = "Engine 2 Condition Lever Position Ecs Channel A",
    [420] = "Engine 3 Condition Lever Position Ecs Channel A",
    [421] = "Engine 4 Condition Lever Position Ecs Channel A",
    [422] = "Engine 1 Throttle Lever Position Ecs Channel B",
    [423] = "Engine 2 Throttle Lever Position Ecs Channel B",
    [424] = "Engine 3 Throttle Lever Position Ecs Channel B",
    [425] = "Engine 4 Throttle Lever Position Ecs Channel B",
    [426] = "Engine 1 Condition Lever Position Ecs Channel B",
    [427] = "Engine 2 Condition Lever Position Ecs Channel B",
    [428] = "Engine 3 Condition Lever Position Ecs Channel B",
    [429] = "Engine 4 Condition Lever Position Ecs Channel B",
    [430] = "Flaps Lever Position",
    [431] = "Slats Lever Position",
    [432] = "Park Brake Lever Position",
    [433] = "Speedbrake Lever Position",
    [434] = "Throttle Max Lever Position",
    [435] = "Pilot Left Brake Pedal Position",
    [436] = "Pilot Right Brake Pedal Position",
    [437] = "Copilot Left Brake Pedal Position",
    [438] = "Copilot Right Brake Pedal Position",
    [439] = "Trim System Switches",
    [440] = "Trim System Lights",
    [441] = "Collective Control Stick Switches",
    [442] = "Stick Shaker Stall Warning Device",
    [500] = "Engine 1 N1 Ecs Channel A",
    [501] = "Engine 2 N1 Ecs Channel A",
    [502] = "Engine 3 N1 Ecs Channel A",
    [503] = "Engine 4 N1 Ecs Channel A",
    [504] = "Engine 1 N2 Ecs Channel A",
    [505] = "Engine 2 N2 Ecs Channel A",
    [506] = "Engine 3 N2 Ecs Channel A",
    [507] = "Engine 4 N2 Ecs Channel A",
    [508] = "Engine 1 Torque Ecs Channel A",
    [509] = "Engine 2 Torque Ecs Channel A",
    [510] = "Engine 3 Torque Ecs Channel A",
    [511] = "Engine 4 Torque Ecs Channel A",
    [512] = "Engine 1 Turbine Inlet Temperature Ecs Channel A",
    [513] = "Engine 2 Turbine Inlet Temperature Ecs Channel A",
    [514] = "Engine 3 Turbine Inlet Temperature Ecs Channel A",
    [515] = "Engine 4 Turbine Inlet Temperature Ecs Channel A",
    [516] = "Engine 1 Inter Turbine Temperature Ecs Channel A",
    [517] = "Engine 2 Inter Turbine Temperature Ecs Channel A",
    [518] = "Engine 3 Inter Turbine Temperature Ecs Channel A",
    [519] = "Engine 4 Inter Turbine Temperature Ecs Channel A",
    [520] = "Engine 1 Turbine Outlet Temperature Ecs Channel A",
    [521] = "Engine 2 Turbine Outlet Temperature Ecs Channel A",
    [522] = "Engine 3 Turbine Outlet Temperature Ecs Channel A",
    [523] = "Engine 4 Turbine Outlet Temperature Ecs Channel A",
    [524] = "Engine 1 Fuel Flow Rate Ecs Channel A",
    [525] = "Engine 2 Fuel Flow Rate Ecs Channel A",
    [526] = "Engine 3 Fuel Flow Rate Ecs Channel A",
    [527] = "Engine 4 Fuel Flow Rate Ecs Channel A",
    [528] = "Engine 1 Manifold Pressure Ecs Channel A",
    [529] = "Engine 2 Manifold Pressure Ecs Channel A",
    [530] = "Engine 3 Manifold Pressure Ecs Channel A",
    [531] = "Engine 4 Manifold Pressure Ecs Channel A",
    [532] = "Engine 1 Oil Pressure Ecs Channel A",
    [533] = "Engine 2 Oil Pressure Ecs Channel A",
    [534] = "Engine 3 Oil Pressure Ecs Channel A",
    [535] = "Engine 4 Oil Pressure Ecs Channel A",
    [536] = "Engine 1 Oil Temperature Ecs Channel A",
    [537] = "Engine 2 Oil Temperature Ecs Channel A",
    [538] = "Engine 3 Oil Temperature Ecs Channel A",
    [539] = "Engine 4 Oil Temperature Ecs Channel A",
    [540] = "Engine 1 Cylinder Head Temperature Ecs Channel A",
    [541] = "Engine 2 Cylinder Head Temperature Ecs Channel A",
    [542] = "Engine 3 Cylinder Head Temperature Ecs Channel A",
    [543] = "Engine 4 Cylinder Head Temperature Ecs Channel A",
    [544] = "Engine 1 Oil Quantity Ecs Channel A",
    [545] = "Engine 2 Oil Quantity Ecs Channel A",
    [546] = "Engine 3 Oil Quantity Ecs Channel A",
    [547] = "Engine 4 Oil Quantity Ecs Channel A",
    [548] = "Engine 1 Coolant Temperature Ecs Channel A",
    [549] = "Engine 2 Coolant Temperature Ecs Channel A",
    [550] = "Engine 3 Coolant Temperature Ecs Channel A",
    [551] = "Engine 4 Coolant Temperature Ecs Channel A",
    [552] = "Engine 1 Power Rating Ecs Channel A",
    [553] = "Engine 2 Power Rating Ecs Channel A",
    [554] = "Engine 3 Power Rating Ecs Channel A",
    [555] = "Engine 4 Power Rating Ecs Channel A",
    [556] = "Engine 1 Status 1 Ecs Channel A",
    [557] = "Engine 2 Status 1 Ecs Channel A",
    [558] = "Engine 3 Status 1 Ecs Channel A",
    [559] = "Engine 4 Status 1 Ecs Channel A",
    [560] = "Engine 1 Status 2 Ecs Channel A",
    [561] = "Engine 2 Status 2 Ecs Channel A",
    [562] = "Engine 3 Status 2 Ecs Channel A",
    [563] = "Engine 4 Status 2 Ecs Channel A",
    [564] = "Engine 1 N1 Ecs Channel B",
    [565] = "Engine 2 N1 Ecs Channel B",
    [566] = "Engine 3 N1 Ecs Channel B",
    [567] = "Engine 4 N1 Ecs Channel B",
    [568] = "Engine 1 N2 Ecs Channel B",
    [569] = "Engine 2 N2 Ecs Channel B",
    [570] = "Engine 3 N2 Ecs Channel B",
    [571] = "Engine 4 N2 Ecs Channel B",
    [572] = "Engine 1 Torque Ecs Channel B",
    [573] = "Engine 2 Torque Ecs Channel B",
    [574] = "Engine 3 Torque Ecs Channel B",
    [575] = "Engine 4 Torque Ecs Channel B",
    [576] = "Engine 1 Turbine Inlet Temperature Ecs Channel B",
    [577] = "Engine 2 Turbine Inlet Temperature Ecs Channel B",
    [578] = "Engine 3 Turbine Inlet Temperature Ecs Channel B",
    [579] = "Engine 4 Turbine Inlet Temperature Ecs Channel B",
    [580] = "Engine 1 Inter Turbine Temperature Ecs Channel B",
    [581] = "Engine 2 Inter Turbine Temperature Ecs Channel B",
    [582] = "Engine 3 Inter Turbine Temperature Ecs Channel B",
    [583] = "Engine 4 Inter Turbine Temperature Ecs Channel B",
    [584] = "Engine 1 Turbine Outlet Temperature Ecs Channel B",
    [585] = "Engine 2 Turbine Outlet Temperature Ecs Channel B",
    [586] = "Engine 3 Turbine Outlet Temperature Ecs Channel B",
    [587] = "Engine 4 Turbine Outlet Temperature Ecs Channel B",
    [588] = "Engine 1 Fuel Flow Rate Ecs Channel B",
    [589] = "Engine 2 Fuel Flow Rate Ecs Channel B",
    [590] = "Engine 3 Fuel Flow Rate Ecs Channel B",
    [591] = "Engine 4 Fuel Flow Rate Ecs Channel B",
    [592] = "Engine 1 Manifold Pressure Ecs Channel B",
    [593] = "Engine 2 Manifold Pressure Ecs Channel B",
    [594] = "Engine 3 Manifold Pressure Ecs Channel B",
    [595] = "Engine 4 Manifold Pressure Ecs Channel B",
    [596] = "Engine 1 Oil Pressure Ecs Channel B",
    [597] = "Engine 2 Oil Pressure Ecs Channel B",
    [598] = "Engine 3 Oil Pressure Ecs Channel B",
    [599] = "Engine 4 Oil Pressure Ecs Channel B",
    [600] = "Engine 1 Oil Temperature Ecs Channel B",
    [601] = "Engine 2 Oil Temperature Ecs Channel B",
    [602] = "Engine 3 Oil Temperature Ecs Channel B",
    [603] = "Engine 4 Oil Temperature Ecs Channel B",
    [604] = "Engine 1 Cylinder Head Temperature Ecs Channel B",
    [605] = "Engine 2 Cylinder Head Temperature Ecs Channel B",
    [606] = "Engine 3 Cylinder Head Temperature Ecs Channel B",
    [607] = "Engine 4 Cylinder Head Temperature Ecs Channel B",
    [608] = "Engine 1 Oil Quantity Ecs Channel B",
    [609] = "Engine 2 Oil Quantity Ecs Channel B",
    [610] = "Engine 3 Oil Quantity Ecs Channel B",
    [611] = "Engine 4 Oil Quantity Ecs Channel B",
    [612] = "Engine 1 Coolant Temperature Ecs Channel B",
    [613] = "Engine 2 Coolant Temperature Ecs Channel B",
    [614] = "Engine 3 Coolant Temperature Ecs Channel B",
    [615] = "Engine 4 Coolant Temperature Ecs Channel B",
    [616] = "Engine 1 Power Rating Ecs Channel B",
    [617] = "Engine 2 Power Rating Ecs Channel B",
    [618] = "Engine 3 Power Rating Ecs Channel B",
    [619] = "Engine 4 Power Rating Ecs Channel B",
    [620] = "Engine 1 Status 1 Ecs Channel B",
    [621] = "Engine 2 Status 1 Ecs Channel B",
    [622] = "Engine 3 Status 1 Ecs Channel B",
    [623] = "Engine 4 Status 1 Ecs Channel B",
    [624] = "Engine 1 Status 2 Ecs Channel B",
    [625] = "Engine 2 Status 2 Ecs Channel B",
    [626] = "Engine 3 Status 2 Ecs Channel B",
    [627] = "Engine 4 Status 2 Ecs Channel B",
    [660] = "Fuel Pump 1 Flow Rate",
    [661] = "Fuel Pump 2 Flow Rate",
    [662] = "Fuel Pump 3 Flow Rate",
    [663] = "Fuel Pump 4 Flow Rate",
    [664] = "Fuel Pump 5 Flow Rate",
    [665] = "Fuel Pump 6 Flow Rate",
    [666] = "Fuel Pump 7 Flow Rate",
    [667] = "Fuel Pump 8 Flow Rate",
    [668] = "Fuel Tank 1 Quantity",
    [669] = "Fuel Tank 2 Quantity",
    [670] = "Fuel Tank 3 Quantity",
    [671] = "Fuel Tank 4 Quantity",
    [672] = "Fuel Tank 5 Quantity",
    [673] = "Fuel Tank 6 Quantity",
    [674] = "Fuel Tank 7 Quantity",
    [675] = "Fuel Tank 8 Quantity",
    [676] = "Fuel Tank 1 Temperature",
    [677] = "Fuel Tank 2 Temperature",
    [678] = "Fuel Tank 3 Temperature",
    [679] = "Fuel Tank 4 Temperature",
    [680] = "Fuel Tank 5 Temperature",
    [681] = "Fuel Tank 6 Temperature",
    [682] = "Fuel Tank 7 Temperature",
    [683] = "Fuel Tank 8 Temperature",
    [684] = "Fuel System 1 Pressure",
    [685] = "Fuel System 2 Pressure",
    [686] = "Fuel System 3 Pressure",
    [687] = "Fuel System 4 Pressure",
    [688] = "Fuel System 5 Pressure",
    [689] = "Fuel System 6 Pressure",
    [690] = "Fuel System 7 Pressure",
    [691] = "Fuel System 8 Pressure",
    [700] = "Rotor 1 Rpm",
    [701] = "Rotor 2 Rpm",
    [702] = "Rotor 3 Rpm",
    [703] = "Rotor 4 Rpm",
    [704] = "Gearbox 1 Speed",
    [705] = "Gearbox 2 Speed",
    [706] = "Gearbox 3 Speed",
    [707] = "Gearbox 4 Speed",
    [708] = "Gearbox 5 Speed",
    [709] = "Gearbox 6 Speed",
    [710] = "Gearbox 7 Speed",
    [711] = "Gearbox 8 Speed",
    [712] = "Gearbox 1 Oil Pressure",
    [713] = "Gearbox 2 Oil Pressure",
    [714] = "Gearbox 3 Oil Pressure",
    [715] = "Gearbox 4 Oil Pressure",
    [716] = "Gearbox 5 Oil Pressure",
    [717] = "Gearbox 6 Oil Pressure",
    [718] = "Gearbox 7 Oil Pressure",
    [719] = "Gearbox 8 Oil Pressure",
    [720] = "Gearbox 1 Oil Temperature",
    [721] = "Gearbox 2 Oil Temperature",
    [722] = "Gearbox 3 Oil Temperature",
    [723] = "Gearbox 4 Oil Temperature",
    [724] = "Gearbox 5 Oil Temperature",
    [725] = "Gearbox 6 Oil Temperature",
    [726] = "Gearbox 7 Oil Temperature",
    [727] = "Gearbox 8 Oil Temperature",
    [728] = "Gearbox 1 Oil Quantity",
    [729] = "Gearbox 2 Oil Quantity",
    [730] = "Gearbox 3 Oil Quantity",
    [731] = "Gearbox 4 Oil Quantity",
    [732] = "Gearbox 5 Oil Quantity",
    [733] = "Gearbox 6 Oil Quantity",
    [734] = "Gearbox 7 Oil Quantity",
    [735] = "Gearbox 8 Oil Quantity",
    [736] = "Gearbox 1 Status",
    [737] = "Gearbox 2 Status",
    [738] = "Gearbox 3 Status",
    [739] = "Gearbox 4 Status",
    [740] = "Gearbox 5 Status",
    [741] = "Gearbox 6 Status",
    [742] = "Gearbox 7 Status",
    [743] = "Gearbox 8 Status",
    [800] = "Hydraulic System 1 Pressure",
    [801] = "Hydraulic System 2 Pressure",
    [802] = "Hydraulic System 3 Pressure",
    [803] = "Hydraulic System 4 Pressure",
    [804] = "Hydraulic System 5 Pressure",
    [805] = "Hydraulic System 6 Pressure",
    [806] = "Hydraulic System 7 Pressure",
    [807] = "Hydraulic System 8 Pressure",
    [808] = "Hydraulic System 1 Fluid Temperature",
    [809] = "Hydraulic System 2 Fluid Temperature",
    [810] = "Hydraulic System 3 Fluid Temperature",
    [811] = "Hydraulic System 4 Fluid Temperature",
    [812] = "Hydraulic System 5 Fluid Temperature",
    [813] = "Hydraulic System 6 Fluid Temperature",
    [814] = "Hydraulic System 7 Fluid Temperature",
    [815] = "Hydraulic System 8 Fluid Temperature",
    [816] = "Hydraulic System 1 Fluid Quantity",
    [817] = "Hydraulic System 2 Fluid Quantity",
    [818] = "Hydraulic System 3 Fluid Quantity",
    [819] = "Hydraulic System 4 Fluid Quantity",
    [820] = "Hydraulic System 5 Fluid Quantity",
    [821] = "Hydraulic System 6 Fluid Quantity",
    [822] = "Hydraulic System 7 Fluid Quantity",
    [823] = "Hydraulic System 8 Fluid Quantity",
    [900] = "Ac System 1 Voltage",
    [901] = "Ac System 2 Voltage",
    [902] = "Ac System 3 Voltage",
    [903] = "Ac System 4 Voltage",
    [904] = "Ac System 5 Voltage",
    [905] = "Ac System 6 Voltage",
    [906] = "Ac System 7 Voltage",
    [907] = "Ac System 8 Voltage",
    [908] = "Ac System 9 Voltage",
    [909] = "Ac System 10 Voltage",
    [910] = "Ac System 1 Current",
    [911] = "Ac System 2 Current",
    [912] = "Ac System 3 Current",
    [913] = "Ac System 4 Current",
    [914] = "Ac System 5 Current",
    [915] = "Ac System 6 Current",
    [916] = "Ac System 7 Current",
    [917] = "Ac System 8 Current",
    [918] = "Ac System 9 Current",
    [919] = "Ac System 10 Current",
    [920] = "Dc System 1 Voltage",
    [921] = "Dc System 2 Voltage",
    [922] = "Dc System 3 Voltage",
    [923] = "Dc System 4 Voltage",
    [924] = "Dc System 5 Voltage",
    [925] = "Dc System 6 Voltage",
    [926] = "Dc System 7 Voltage",
    [927] = "Dc System 8 Voltage",
    [928] = "Dc System 9 Voltage",
    [929] = "Dc System 10 Voltage",
    [930] = "Dc System 1 Current",
    [931] = "Dc System 2 Current",
    [932] = "Dc System 3 Current",
    [933] = "Dc System 4 Current",
    [934] = "Dc System 5 Current",
    [935] = "Dc System 6 Current",
    [936] = "Dc System 7 Current",
    [937] = "Dc System 8 Current",
    [938] = "Dc System 9 Current",
    [939] = "Dc System 10 Current",
    [940] = "Prop 1 Iceguard Dc Current",
    [941] = "Prop 2 Iceguard Dc Current",
    [942] = "Prop 3 Iceguard Dc Current",
    [943] = "Prop 4 Iceguard Dc Current",
    [944] = "Prop 5 Iceguard Dc Current",
    [945] = "Prop 6 Iceguard Dc Current",
    [946] = "Prop 7 Iceguard Dc Current",
    [947] = "Prop 8 Iceguard Dc Current",
    [948] = "Prop 9 Iceguard Dc Current",
    [949] = "Prop 10 Iceguard Dc Current",
    [1000] = "Active Nav System Waypoint Latitude",
    [1001] = "Active Nav System Waypoint Longitude",
    [1002] = "Active Nav System Waypoint Height Above Ellipsoid",
    [1003] = "Active Nav System Waypoint Altitude",
    [1004] = "Active Nav System Ground Speed",
    [1005] = "Active Nav System True Track",
    [1006] = "Active Nav System Magnetic Track",
    [1007] = "Active Nav System Cross Track Error",
    [1008] = "Active Nav System Track Error Angle",
    [1009] = "Active Nav System Time To Go",
    [1010] = "Active Nav System Estimated Time Of Arrival",
    [1011] = "Active Nav System Estimated Enroute Time",
    [1012] = "Nav Waypoint Identifier 0 3",
    [1013] = "Nav Waypoint Identifier 4 7",
    [1014] = "Nav Waypoint Identifier 8 11",
    [1015] = "Nav Waypoint Identifier 12 15",
    [1016] = "Nav Waypoint Type Identifier",
    [1017] = "Nav Waypoint Latitude",
    [1018] = "Nav Waypoint Longitude",
    [1019] = "Nav Waypoint Minimum Altitude",
    [1020] = "Nav Waypoint Minimum Flight Level",
    [1021] = "Nav Waypoint Minimum Radar Height",
    [1022] = "Nav Waypoint Minimum Height Above Ellipsoid",
    [1023] = "Nav Waypoint Maximum Altitude",
    [1024] = "Nav Waypoint Maximum Flight Level",
    [1025] = "Nav Waypoint Maximum Radar Height",
    [1026] = "Nav Waypoint Maximum Height Above Ellipsoid",
    [1027] = "Nav Waypoint Planned Altitude",
    [1028] = "Nav Waypoint Planned Flight Level",
    [1029] = "Nav Waypoint Planned Radar Height",
    [1030] = "Nav Waypoint Planned Height Above Ellipsoid",
    [1031] = "Distance To Nav Waypoint",
    [1032] = "Time To Go To Nav Waypoint",
    [1033] = "Nav Waypoint Estimated Time Of Arrival",
    [1034] = "Nav Waypoint Estimated Enroute Time",
    [1035] = "Nav Waypoint Status Information",
    [1036] = "Gps Aircraft Latitude",
    [1037] = "Gps Aircraft Longitude",
    [1038] = "Gps Aircraft Height Above Ellipsoid",
    [1039] = "Gps Ground Speed",
    [1040] = "Gps True Track",
    [1041] = "Gps Magnetic Track",
    [1042] = "Gps Cross Track Error",
    [1043] = "Gps Track Error Angle",
    [1044] = "Gps Glideslope Deviation",
    [1045] = "Gps Predicted Raim",
    [1046] = "Gps Vertical Figure Of Merit",
    [1047] = "Gps Horizontal Figure Of Merit",
    [1048] = "Gps Mode Of Operation",
    [1049] = "Ins Aircraft Latitude",
    [1050] = "Ins Aircraft Longitude",
    [1051] = "Ins Aircraft Height Above Ellipsoid",
    [1052] = "Ins Aircraft Ground Speed",
    [1053] = "Ins Aircraft True Track",
    [1054] = "Ins Aircraft Magnetic Track",
    [1055] = "Ins Aircraft Cross Track Error",
    [1056] = "Ins Aircraft Track Error Angle",
    [1057] = "Ins Vertical Figure Of Merit",
    [1058] = "Ins Horizontal Figure Of Merit",
    [1059] = "Auxiliary Nav System Aircraft Latitude",
    [1060] = "Auxiliary Nav System Aircraft Longitude",
    [1061] = "Auxiliary Nav System Aircraft Height Above Ellipsoid",
    [1062] = "Auxiliary Nav System Aircraft Ground Speed",
    [1063] = "Auxiliary Nav System Aircraft True Track",
    [1064] = "Auxiliary Nav System Aircraft Magnetic Track",
    [1065] = "Auxiliary Nav System Aircraft Cross Track Error",
    [1066] = "Auxiliary Nav System Aircraft Track Error Angle",
    [1067] = "Auxiliary Nav System Vertical Figure Of Merit",
    [1068] = "Auxiliary Nav System Horizontal Figure Of Merit",
    [1069] = "Magnetic Heading",
    [1070] = "Radio Height",
    [1071] = "Dme 1 Distance",
    [1072] = "Dme 2 Distance",
    [1073] = "Dme 3 Distance",
    [1074] = "Dme 4 Distance",
    [1075] = "Dme 1 Time To Go",
    [1076] = "Dme 2 Time To Go",
    [1077] = "Dme 3 Time To Go",
    [1078] = "Dme 4 Time To Go",
    [1079] = "Dme 1 Ground Speed",
    [1080] = "Dme 2 Ground Speed",
    [1081] = "Dme 3 Ground Speed",
    [1082] = "Dme 4 Ground Speed",
    [1083] = "Adf 1 Bearing",
    [1084] = "Adf 2 Bearing",
    [1085] = "Adf 3 Bearing",
    [1086] = "Adf 4 Bearing",
    [1087] = "Ils 1 Localizer Deviation",
    [1088] = "Ils 2 Localizer Deviation",
    [1089] = "Ils 3 Localizer Deviation",
    [1090] = "Ils 4 Localizer Deviation",
    [1091] = "Ils 1 Glideslope Deviation",
    [1092] = "Ils 2 Glideslope Deviation",
    [1093] = "Ils 3 Glideslope Deviation",
    [1094] = "Ils 4 Glideslope Deviation",
    [1095] = "Flight Director 1 Pitch Deviation",
    [1096] = "Flight Director 2 Pitch Deviation",
    [1097] = "Flight Director 1 Roll Deviation",
    [1098] = "Flight Director 2 Roll Deviation",
    [1099] = "Decision Height",
    [1100] = "Vhf 1 Com Frequency",
    [1101] = "Vhf 2 Com Frequency",
    [1102] = "Vhf 3 Com Frequency",
    [1103] = "Vhf 4 Com Frequency",
    [1104] = "Vor Ils 1 Frequency",
    [1105] = "Vor Ils 2 Frequency",
    [1106] = "Vor Ils 3 Frequency",
    [1107] = "Vor Ils 4 Frequency",
    [1108] = "Adf 1 Frequency",
    [1109] = "Adf 2 Frequency",
    [1110] = "Adf 3 Frequency",
    [1111] = "Adf 4 Frequency",
    [1112] = "Dme 1 Channel",
    [1113] = "Dme 2 Channel",
    [1114] = "Dme 3 Channel",
    [1115] = "Dme 4 Channel",
    [1116] = "Transponder 1 Code",
    [1117] = "Transponder 2 Code",
    [1118] = "Transponder 3 Code",
    [1119] = "Transponder 4 Code",
    [1120] = "Desired Track Angle",
    [1121] = "Magnetic Variation",
    [1122] = "Selected Glidepath Angle",
    [1123] = "Selected Runway Heading",
    [1124] = "Computed Vertical Velocity",
    [1125] = "Selected Course",
    [1126] = "Vor 1 Radial",
    [1127] = "Vor 2 Radial",
    [1128] = "Vor 3 Radial",
    [1129] = "Vor 4 Radial",
    [1130] = "True East Velocity",
    [1131] = "True North Velocity",
    [1132] = "True Up Velocity",
    [1133] = "True Heading",
    [1134] = "GPS geoid separation",
    [1135] = "GPS SV info, one message per SV",
    [1175] = "Gear Lever Switches",
    [1176] = "Gear Lever Lights Wow Solenoid",
    [1177] = "Landing Gear 1 Tire Pressure",
    [1178] = "Landing Gear 2 Tire Pressure",
    [1179] = "Landing Gear 3 Tire Pressure",
    [1180] = "Landing Gear 4 Tire Pressure",
    [1181] = "Landing Gear 1 Brake Pad Thickness",
    [1182] = "Landing Gear 2 Brake Pad Thickness",
    [1183] = "Landing Gear 3 Brake Pad Thickness",
    [1184] = "Landing Gear 4 Brake Pad Thickness",
    [1185] = "Landing Gear 1 Status",
    [1186] = "Landing Gear 2 Status",
    [1187] = "Landing Gear 3 Status",
    [1188] = "Landing Gear 4 Status",
    [1189] = "Landing Gear 1 Extension Retraction Status",
    [1190] = "Landing Gear 2 Extension Retraction Status",
    [1191] = "Landing Gear 3 Extension Retraction Status",
    [1192] = "Landing Gear 4 Extension Retraction Status",
    [1193] = "Brake System 1 Pressure",
    [1194] = "Brake System 2 Pressure",
    [1195] = "Brake System 3 Pressure",
    [1196] = "Brake System 4 Pressure",
    [1197] = "Brake System 1 Status",
    [1198] = "Brake System 2 Status",
    [1199] = "Brake System 3 Status",
    [1200] = "Utc",
    [1201] = "Cabin Pressure",
    [1202] = "Cabin Altitude",
    [1203] = "Cabin Temperature",
    [1204] = "Longitudinal Center Of Gravity",
    [1205] = "Lateral Center Of Gravity",
    [1206] = "Date",
    [1207] = "Weight",
    [1208] = "Fuel Weight",
    [1209] = "Zero Fuel Weight",

    [1300] = "Flarm State",
    [1301] = "FLAA AL 3",
    [1302] = "FLAA AL 2",
    [1303] = "FLAA AL 1",
    [1304] = "FLAA AL 0",
    [1305] = "ADSB State",

    [1500] = "ISU Sensor board temperature",
    [1501] = "ISU QFF estimate",
    [1502] = "ISU AHRS accelerometer bias estimate body ax X",
    [1503] = "ISU AHRS accelerometer bias estimate body ax Y",
    [1504] = "ISU AHRS accelerometer bias estimate body ax Z",
    [1506] = "State of IGC flight recorder unit",
    [1507] = "IGC flight recorder command NODATA means PILOT EVENT",
    [1509] = "Retractable engine position",
    [1510] = "Vario meter mode 0=variometer 1=speedcommand",
    [1511] = "Voice mute, 1=mutes",
    [1512] = "Audio and Volume broadcast",
    [1513] = "glide polar coefficients, servicecode is 0=A,B,2=C",
    [1514] = "glide polar bugs",
    [1515] = "glide polar mass dry and ballast [ushort kg*10^1]",
    [1516] = "glide polar pilot mass (dry payload) -> empty-mass + pilot-mass + ballast-mass = takeoff-mass [ushort kg*10^1]",
    [1517] = "wind override AS_UCHAR == 1 override",
    [1518] = "Expected Lift, the classic McCrady value",
    [1519] = "barometric altitude corretion in meters: altQNH = altSTD + <value> (SC=0: QNH, SC=1: QFE)",
    [1520] = "magnetometer flux vector NORTH component in uT",
    [1521] = "magnetometer flux vector EAST component in uT",
    [1522] = "magnetometer flux vector DOWN component in uT",
    [1530] = "voice message ID",
    [1600] = "RU stream",
    [1601] = "state of magneto calibration",
    [1610] = "Route name, multiple zero terminated",
    [1611] = "Route description, multiple zero terminated",
    [1612] = "waypoint name, multiple zero terminated",
    [1613] = "waypoint route segment type (reserved)",
    [1614] = "waypoint latitude",
    [1615] = "waypoint longitude",
    [1616] = "waypoint altitude",
    [1798] = "CPT6100 PRESS ID",
    [1799] = "LAST USER DEFINED ID / NOD LAST",
    [1800] = "who am i SC=0: S/N SC=1: P/N rate: 0.1 .. 1 hz",
    [1209] = "Zero Fuel Weight"
}

-- CANAerospace node_id
-- WIP: to be extended/changed !
utils.defaultNodeIdTable = {
    [01] = "AHRS",
    [02] = "ADC",
    [03] = "VHF1",
    [04] = "VHF2",
    [05] = "NAVILS1",
    [06] = "NAVILS2",
    [07] = "ATC",
    [08] = "ADF",

    [10] = "GPS",
    [11] = "DME",
    [12] = "EMS",
    [13] = "ETS",
    [14] = "ES",
    [15] = "WCS"
}

-- Data types
utils.dataTypeTable = {
    [0x00] = "NODATA",
    [0x01] = "ERROR",
    [0x02] = "FLOAT",
    [0x03] = "LONG",
    [0x04] = "ULONG",
    [0x05] = "BLONG",
    [0x06] = "SHORT",
    [0x07] = "USHORT",
    [0x08] = "BSHORT",
    [0x09] = "CHAR",
    [0x0A] = "UCHAR",
    [0x0B] = "BCHAR",
    [0x0C] = "SHORT2",
    [0x0D] = "USHORT2",
    [0x0E] = "BSHORT2",
    [0x0F] = "CHAR4",
    [0x10] = "UCHAR4",
    [0x11] = "BCHAR4",
    [0x12] = "CHAR2",
    [0x13] = "UCHAR2",
    [0x14] = "BCHAR2",
    [0x15] = "MEMID",
    [0x16] = "CHKSUM",
    [0x17] = "ACHAR",
    [0x18] = "ACHAR2",
    [0x19] = "ACHAR4",
    [0x1A] = "CHAR3",
    [0x1B] = "UCHAR3",
    [0x1C] = "BCHAR3",
    [0x1D] = "ACHAR3",
    [0x1E] = "DOUBLEH",
    [0x1F] = "DOUBLEL",
    [0x20] = "RESVD",
    [0x64] = "UDEF"
}

-- CANAerospace service_code
utils.serviceCodeTable = {
    [0x00] = "SC0",
    [0x01] = "SC1",
    [0x02] = "SC2",
    [0x03] = "SC3",
    [0x04] = "SC4",
    [0x05] = "SC5",
    [0x06] = "SC6",
    [0x07] = "SC7",
    [0x08] = "SC8"
}

return utils
